### ISSUE TITLE
Discussion: TaskSlim continuation

### ISSUE THREAD

**Issue by danielmarbach** [clearctvm/RabbitMqNext#1]
https://github.com/clearctvm/RabbitMqNext/blob/e23b098f0a135c0f3b3882d144936e579f7b06a2/src/RabbitMqNext/TplExtensions/BaseTaskSlim.cs#L140

Judging based on your usage I have a hunch you could hint on the continuation to [execute it synchronously](https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskcontinuationoptions%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396). Or do you explicitly want/need to schedule the continuation?

**Comment by hammett** [comment]
The issue here is being able to re-use the Task objects. Since the original task cannot be reused, this is a slim version with less capabilities but that can be recycled and supports sync/async exec of the continuation.

**Comment by danielmarbach** [comment]
Sorry I meant does the recycle call need to happen on a scheduled task which is potentially picked up by another worker thread or could you call the recycle continuation with the ExecuteSynchronously flag?

**Comment by hammett** [comment]
I believe it doesnt matter which thread fires the recycling process. The recycling code is quite short and the item may or may not go back to the pool, depending on the state of the objpool

https://github.com/clearctvm/RabbitMqNext/blob/writing_opt/src/RabbitMqNext/Buffers/ObjectPool.cs

**Comment by danielmarbach** [comment]
Even if you specify `ExecuteSynchronously` it is just a hint for the scheduler. It can still mean it will be scheduled. I'd use it here but I have no strong arguments against not using it.

**Comment by hammett** [comment]
Not sure I follow you here? The TaskSlim is mimic'ing the TPL, but has its own semantics.
