### ISSUE TITLE
Make OnError events Task based

### ISSUE THREAD

**Issue by ChristianBryanAPC** [clearctvm/RabbitMqNext#12]
Any chance of making the OnError event on both the channel and connection to be more akin to the way you can register a callback function e.g Func<amqpError, Task for the BasicConsume method. I am using Akka.Net to wrap the RabbiitMqNext client up, as the current RabbiitMQ client is heavily EAP based, this is a pain to wrap up into tasks to play nicely with Akka.Net. This is the reason which drove me to RabbitMqNext in the first place as I could do a BasicConsume on RabbiitMQNext passing a function to return a task in which I could pipe the message received back into my channel actor.

**Comment by hammett** [comment]
Sure.

**Comment by ChristianBryanAPC** [comment]
Thank you

**Comment by hammett** [comment]
This makes it a bit harder:

> Void-returning async methods have a specific purpose: to make asynchronous event handlers possible. It is possible to have an event handler that returns some actual type, but that doesn't work well with the language; invoking an event handler that returns a type is very awkward, and the notion of an event handler actually returning something doesn't make much sense. Event handlers naturally return void, so async methods return void so that you can have an asynchronous event handler. However, some semantics of an async void method are subtly different than the semantics of an async Task or async Task<T> method.

https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

I'd have to remove the event and instead use RegisterErrorCallback or something equivalent. Is this what you're looking for?

**Comment by ChristianBryanAPC** [comment]
Hammet, essentially yes I am looking for a method to register a callback.
