### ISSUE TITLE
Tag releases to match NuGet versions

### ISSUE THREAD

**Issue by bording** [clearctvm/RabbitMqNext#14]
When you push a new version to NuGet, can you make sure you also push up a tag on the repo? Without doing that, it's far too hard to figure out what changes are included in the package!

**Comment by hammett** [comment]
Once the publishing is handled by Appveyor, that should happen automatically. PRs are welcome

**Comment by adamralph** [comment]
@hammett can you please explain how a PR would solve this issue?

**Comment by hammett** [comment]
The appveyor config is in the repository for anyone willing to do the heavy lifting.

**Comment by adamralph** [comment]
But how would you control what goes out to nuget? Every commit to master?
Then you need an appropriate branching strategy if you want allow
intermittent commits between releases. Also, where would the version number
come from?

Unless I'm missing something, I don't think a PR alone can solve this.

**Comment by hammett** [comment]
I only commit to master if the tests + integration pass. So that's already a policy. No changes.
