### ISSUE TITLE
Connection recovery now throwing Exception: Cannot Set when operational

### ISSUE THREAD

**Issue by ChristianBryanAPC** [clearctvm/RabbitMqNext#17]
Connection recovery used to work a few versions ago, with the connection restored and all the channels recreated. Now when I manually terminate the connection in RabbitMQ's management console a recovery attempt is made but then throws a 'Cannot Set when operational' exception. Is it me or has channel recovery got borked in some way?

**Comment by hammett** [comment]
Thanks for catching this up. I'll take a look when I get a chance.

**Comment by ChristianBryanAPC** [comment]
Cheers for the fix, any chance of a Nuget version bump?

**Comment by hammett** [comment]
as soon as I complete the fix for the RPC bug
