### ISSUE TITLE
Setting headers

### ISSUE THREAD

**Issue by volak** [clearctvm/RabbitMqNext#19]
I'm playing around a bit with this as an alternative to the official client but I noticed there is no way to set headers on BasicProperties?

**Comment by hammett** [comment]
BasicProperties.Headers["key"] = value; should do the trick.

**Comment by volak** [comment]
Ah you are right that would work I was looking at setting all the headers in one go and got confused.  

But while I was looking at this I stumbled into a couple other problems that I just committed a fix for here: https://github.com/volak/RabbitMqNext/commit/5bfcf4ef01327dde6d1a1f76dea5a2350f1e8339

One major thing is when BasicProperties is disposed you call .Clear() on headers which throws an exception if its a ReadonlyDictionary.  Seems like Frozen is not used often at all but that would happen.  Also when frozen headers will always be empty.

But I was also having problems with ReadTable on BasicDelivery - so I modified it to spit out a enumerable of KeyValuePairs instead of instantiating the fixed capacity dict.

Let me know what you think, I guess I didn't need to dig this much but Im doing a little side project and perhaps stayed awake a bit too long.

**Comment by hammett** [comment]
Interesting point on the Clear call, I'll take a look. 

Regarding the other changes:
- the headers should be owned by the BP, that's why I removed the property setter 
- BP go in an objectpool, using the Rent/Return pattern (with implicit return on some calls - I guess I need to document those), that's why there's the Dispose/bits being set.
- Given the two points above, I dont think the ReadTable change make sense, unless I'm missing some scenario I haven't anticipated.

**Comment by volak** [comment]
Yeah that makes sense - I am just completing a nservicebus rabbitmq fork to use this client instead of the official.  They do properties.Headers = {} in several places I just didnt realize what I was doing.

While I got you here though - does https://github.com/clearctvm/RabbitMqNext/blob/master/src/RabbitMqNext/Internals/MessagesPendingConfirmationKeeper.cs#L60 and https://github.com/clearctvm/RabbitMqNext/blob/master/src/RabbitMqNext/Internals/MessagesPendingConfirmationKeeper.cs#L67 need to be warnings?

I hooked up NSB's logging to your adaptor and my screens are filling up with dangerous time it took to confirm messages

**Comment by hammett** [comment]
Nah, those are leftover from a bug chasing session. Feel free to remove them.

**Comment by volak** [comment]
One more thing - I have no idea why NSB does this but they use ConnectionFactory all the time to create new connections to Rabbitmq.  

such as 
```
            using (var connection = await connectionFactory.CreateConnection("Consume"))
            using (var channel = await connection.CreateChannel())
```

used for just 1 operation.  

When I ported the factory into your code I found once the connection is disposed it seems the reading and writing threads are killed and even starting a new connection won't bring them back.  Is it recommended for your code base to keep the connection around?

**Comment by hammett** [comment]
> used for just 1 operation.
What's the operation? 
It's a significant overhead. This client specifically allocates a ringbuffer on the LOH per connection, so it's *not efficient at all* to have all this up, doing some minor operation, and tearing them down. 

> reading and writing threads are killed and even starting a new connection won't bring them back.
The read frame and writer threads are per connection.

**Comment by volak** [comment]
Good example: https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.RabbitMQ/Administration/SubscriptionManager.cs

For the main message pump they hold onto 1 connection, but for all the little things like subscribing to queues or creating exchanges its all one-shot connections.  Very weird.  Totally makes sense to me that my apps start faster now

**Comment by hammett** [comment]
The guidance is actually the opposite: have a connection per queue subscription (assuming they are high traffic).
Absolute no need to create a connection just to set up an exchange and bindings. This is terrible, regardless of the client.

**Comment by volak** [comment]
Thanks for the help - heres the project I just launched to use NServiceBus using this client https://github.com/volak/NServiceBus.RabbitMQNext

Performance is.. fantastic 👍

**Comment by hammett** [comment]
Looks good. We do support NAck, though, if that's what you mean by rejecting a message.

**Comment by volak** [comment]
I haven't looked deeply into it, but what NSB is trying to do is send back a received message.  Not just negatively acknowledging.  They are using BasicReject in rabbitmq official client which I couldn't find.

**Comment by hammett** [comment]
Looks like it's the same thing: https://www.rabbitmq.com/nack.html

**Comment by volak** [comment]
Fantastic - then it will be really easy to replace that NotImplementedException
