### ISSUE TITLE
Discussion: ConfigureAwait

### ISSUE THREAD

**Issue by danielmarbach** [clearctvm/RabbitMqNext#2]
Out of curiosity: Is there a reason why you don't use `ConfigureAwait(false)` for your internal lib awaits?

**Comment by hammett** [comment]
No reason, just hasnt been an issue yet. May as well become one when I test it on asp.net :-(

**Comment by danielmarbach** [comment]
If you want I can contribute it

**Comment by hammett** [comment]
Please do! that would be awesome. Thanks!

**Comment by danielmarbach** [comment]
Done as part of #5
