### ISSUE TITLE
Introduce gitattributes and optionally editor.config

### ISSUE THREAD

**Issue by danielmarbach** [clearctvm/RabbitMqNext#8]
For example https://github.com/Particular/NServiceBus/blob/develop/.gitattributes (we have good success with this)

and optionally http://editorconfig.org/

**Comment by hammett** [comment]
Done. Wasnt aware of this. Thanks for bringing it up

**Comment by danielmarbach** [comment]
See also

https://help.github.com/articles/dealing-with-line-endings/

Especially the refresh part

**Comment by danielmarbach** [comment]
See inline comment on commit

**Comment by hammett** [comment]
Fixed! Sorry
