### ISSUE TITLE
Q: Publish RabbitMqNext to NuGet?

### ISSUE THREAD

**Issue by pardahlman** [clearctvm/RabbitMqNext#9]
Great work with this alternative client :+1: Are there any plans of publishing the `RabbitMqNext` client on NuGet? Do you know of any organisation using this client in production (the `README` states that it is not production ready, but I thought I'd check).

**Comment by hammett** [comment]
Hi @pardahlman . We're pushing it this month to production. Regarding nuget, I think the spec is ready, I just need to do it. Will try to do it this weekend. 

Cheers!

**Comment by hammett** [comment]
Published https://www.nuget.org/packages/RabbitMqNext/
